/* omacord palette - generated by Omarchy from the active theme's colors.toml.
 * Do not edit: rewritten on every `omarchy theme set`.
 * Variables only, no selectors. base.css consumes these with fallbacks. */

:root {
  --omacord-scheme: {{ mode }};

  /* Surfaces, recessed -> elevated.
   * s0..s2 come from the theme directly; s3/s4 are mixed toward the
   * foreground so they contrast in light and dark themes alike
   * (lighter_background is not reliably lighter than background). */
  --omacord-s0: {{ darker_background }};
  --omacord-s1: {{ dark_background }};
  --omacord-s2: {{ background }};
  --omacord-s3: {{ mix background foreground 6% }};
  --omacord-s4: {{ mix background foreground 12% }};

  /* Text */
  --omacord-tx:        {{ foreground }};
  --omacord-tx-strong: {{ bright_foreground }};
  --omacord-tx-dim:    {{ dark_foreground }};
  --omacord-tx-faint:  {{ mix background foreground 45% }};

  /* Accent. --omacord-on-accent is the readable text colour on an accent
   * fill: the theme background is always the far end of the contrast
   * range from its own accent, in either mode. */
  --omacord-accent:       {{ accent }};
  --omacord-accent-hover: {{ mix accent bright_foreground 20% }};
  --omacord-accent-dim:   {{ mix background accent 35% }};
  --omacord-accent-faint: {{ mix background accent 12% }};
  --omacord-on-accent:    {{ background }};

  /* Lines. Matched to Hyprland's border weight. */
  --omacord-border:        {{ mix background foreground 20% }};
  --omacord-border-strong: {{ mix background foreground 35% }};
  --omacord-hover:         {{ mix background foreground 8% }};
  --omacord-active:        {{ mix background foreground 16% }};

  /* Selection */
  --omacord-sel:    {{ selection_background }};
  --omacord-sel-fg: {{ selection_foreground }};
  --omacord-muted:  {{ muted }};

  /* Hues */
  --omacord-red:     {{ red }};
  --omacord-green:   {{ green }};
  --omacord-yellow:  {{ yellow }};
  --omacord-orange:  {{ orange }};
  --omacord-blue:    {{ blue }};
  --omacord-cyan:    {{ cyan }};
  --omacord-magenta: {{ magenta }};

  --omacord-bright-red:     {{ bright_red }};
  --omacord-bright-green:   {{ bright_green }};
  --omacord-bright-yellow:  {{ bright_yellow }};
  --omacord-bright-blue:    {{ bright_blue }};
  --omacord-bright-cyan:    {{ bright_cyan }};
  --omacord-bright-magenta: {{ bright_magenta }};

  /* Channels, for alpha compositing */
  --omacord-bg-rgb:     {{ background_rgb }};
  --omacord-fg-rgb:     {{ foreground_rgb }};
  --omacord-accent-rgb: {{ accent_rgb }};
  --omacord-s0-rgb:     {{ darker_background_rgb }};
}
