-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Lenovo Group Limited 0x9052",
  mode = "1920x1080@60.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Lenovo Group Limited 0x9052", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Lenovo Group Limited 0x9052" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Lenovo Group Limited 0x9052" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Lenovo Group Limited 0x9052" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Lenovo Group Limited 0x9052" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Lenovo Group Limited 0x9052" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Lenovo Group Limited 0x9052" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Lenovo Group Limited 0x9052" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Lenovo Group Limited 0x9052" })
