-- Generated by OmaSettings (omasettings:managed) — do not edit by hand.
-- Every value here was set from the OmaSettings window; delete a line
-- to hand that setting back to your own config.

hl.config({
  animations = {
    workspace_wraparound = true,
  },
})

hl.config({
  decoration = {
    blur = {
      enabled = true,
      contrast = 0.30,
      passes = 3,
      popups = true,
      size = 6,
      special = true,
      vibrancy = 0.16,
      vibrancy_darkness = 0.03,
      xray = true,
    },
    dim_inactive = true,
    glow = {
      range = 3,
      render_power = 1,
    },
    shadow = {
      enabled = true,
      range = 16,
    },
  },
})

hl.config({
  general = {
    border_size = 3,
    float_gaps = 16,
    gaps_in = 6,
    gaps_out = 6,
    gaps_workspaces = 32,
    snap = {
      enabled = true,
      monitor_gap = 6,
      window_gap = 6,
    },
  },
})


-- Full opacity: Omarchy tags every window and fades it to 0.985, which
-- multiplies with the opacity settings, so 100% renders at 98.5%.
o.window(".*", { opacity = "1.0 1.0" })

-- Animation speed: Omarchy's own set, every speed multiplied by 0.80.
hl.animation({ leaf = "global", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 4.312, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 3.032, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 3.28, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.192, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.384, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.168, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 2.424, bezier = "quick" })
hl.animation({ leaf = "fadeSwitch", enabled = false })
hl.animation({ leaf = "layers", enabled = true, speed = 3.048, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 3.2, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.2, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.432, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.112, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = false })
